name: Node.js Package

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: |
          cd playwright
          pnpm install
      - run: |
          cd playwright
          pnpm run test
      - run: |
          cd playwright
          pnpm run build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: |
          cd playwright
          pnpm install
      - run: |
          cd playwright
          pnpm run build
      - run: |
          cd playwright
          npm publish
